project:
  type: website
  output-dir: docs/_site

website:
  title: "NBA Analytics Suite"
  navbar:
    left:
      - text: "Home"
        href: docs/index.qmd
      - text: "Tutorial"
        href: docs/tutorial.qmd
      - text: "Report"
        href: docs/report.qmd
      - text: "Documentation"
        href: docs/documentation.qmd

format:
  html:
    theme: flatly
    toc: true


