project:
  type: website

website:
  title: "NBA Analytics Suite"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Tutorial"
        href: tutorial.html
      - text: "Report"
        href: report.html
      - text: "Documentation"
        href: documentation.html

format:
  html:
    theme: flatly
    toc: true



